Repository felixfaisal/formica, pull requests merged in 2021-06, with the labels that each got.

#63 PR template added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: LGM SOC, LGTM

#67 Updated Readme
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: LGMSOC21, Level2, documentation

#70 Added License and Project Admin
  README.md
Labels: LGMSOC21, Level2

#74 Open source section added #72
  README.md
Labels: LGMSOC21, Level1

#83 badges added with links
  README.md
Labels: LGMSOC21, Level1
