Repository felixfaisal/formica, pull requests merged in 2021-10, with the labels that each got.

#86 Added a different docker-compose file for dev env
  backend/dev.Dockerfile
  bot/dev.Dockerfile
  docker-compose.dev.yml
  frontend/Dockerfile
  frontend/dev.Dockerfile
  frontend/package-lock.json
  frontend/yarn.lock
Labels: docker, hacktoberfest, hacktoberfest-accepted

#90 Fix some of the flake8 issues.
  backend/API/admin.py
  backend/API/auth.py
  backend/API/helper.py
  backend/API/managers.py
  backend/API/models.py
  backend/API/serializer.py
  backend/API/tests.py
  backend/API/urls.py
  backend/API/views.py
Labels: LGTM, hacktoberfest, hacktoberfest-accepted

#91 [CI] Changes to docker file of frontend
  .github/workflows/docker-image.yml
  docker-compose.dev.yml
  frontend/dev.Dockerfile
  frontend/package-lock.json
  frontend/yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted
